import { drizzle } from "drizzle-orm/mysql2";
import { env } from "../api/lib/env";
import * as schema from "./schema";

const db = drizzle(env.databaseUrl, { mode: "planetscale", schema });

async function seed() {
  console.log("Seeding OpenIntel with Shroud of Turin case...");

  // ── CASE ──
  const [caseRow] = await db.insert(schema.cases).values({
    caseId: "OI-CT-SHROUD",
    canonicalTitle: "Shroud of Turin",
    caseType: "PHENOMENON",
    category: "Religious Artifact / Forensic Phenomenon",
    status: "ACTIVE",
    oneSentenceVerdict: null,
    ocsScore: null,
    verdict: null,
    notes: "Universal truth-finding protocol proof-of-concept. Fakery Matrix F1-F10 yields functionally zero compound probability for forgery. Population Density Test yields zero required forger population.",
  }).$returningId();

  const caseId = caseRow.id;
  console.log(`Created case: ${caseId}`);

  // ── EVIDENCE: DOMAIN 1 — MATERIAL SCIENCE ──
  await db.insert(schema.evidenceItems).values([
    { caseId, domain: "MATERIAL_SCIENCE", evidenceName: "Pure linen, flax plant, 3:1 herringbone weave", tier: "T1", source: "STURP 1978, textile analysis", whatItProves: "Wealthy burial cloth, consistent with Joseph of Arimathea", fabricationCost: "EXTREME", fabricationCostDescription: "Cannot replicate exact weave structure from 1st century", counterArguments: "None - never disputed", isDiscriminating: "true", yearDiscovered: 1978 },
    { caseId, domain: "MATERIAL_SCIENCE", evidenceName: "Dimensions: 14'4\" x 3'7\" (8.8 x 2 Assyrian cubits)", tier: "T1", source: "Direct measurement", whatItProves: "Standard Roman Empire unit of measurement", fabricationCost: "HIGH", counterArguments: "Coincidence possible but unlikely", isDiscriminating: "true" },
    { caseId, domain: "MATERIAL_SCIENCE", evidenceName: "Image only 2 microns deep", tier: "T1", source: "STURP microchemical analysis", whatItProves: "Superficial discoloration of topmost fibrils only - no substance applied", fabricationCost: "IMPOSSIBLE", fabricationCostDescription: "No known technology achieves this precision", counterArguments: "None - never replicated", isDiscriminating: "true", yearDiscovered: 1978 },
    { caseId, domain: "MATERIAL_SCIENCE", evidenceName: "No paint, dye, pigment, or ink present", tier: "T1", source: "STURP (Schwalbe & Rogers 1982)", whatItProves: "Peer-reviewed, never overturned - image is not artistic", fabricationCost: "EXTREME", counterArguments: "McCrone's iron oxide claim debunked by superior methods", isDiscriminating: "true", yearDiscovered: 1982 },
    { caseId, domain: "MATERIAL_SCIENCE", evidenceName: "Blood penetrates fully; image does not", tier: "T1", source: "STURP", whatItProves: "Different mechanisms - blood is contact transfer, image is not", fabricationCost: "HIGH", counterArguments: "None", isDiscriminating: "true", yearDiscovered: 1978 },
    { caseId, domain: "MATERIAL_SCIENCE", evidenceName: "Image survives 3+ fires and water damage", tier: "T1", source: "Historical + conservation record", whatItProves: "No smearing, dilution, or degradation - inherently permanent", fabricationCost: "EXTREME", counterArguments: "None", isDiscriminating: "true" },
    { caseId, domain: "MATERIAL_SCIENCE", evidenceName: "Chemical change to fibrils (oxidation/dehydration)", tier: "T1", source: "STURP", whatItProves: "Not an applied substance - molecular alteration of cellulose", fabricationCost: "EXTREME", counterArguments: "None", isDiscriminating: "true", yearDiscovered: 1978 },
    { caseId, domain: "MATERIAL_SCIENCE", evidenceName: "Zero vanillin remaining (Rogers 2005)", tier: "T2", source: "Thermochimica Acta 2005, peer-reviewed", whatItProves: "Zero vanillin = ancient (>1300 years old)", fabricationCost: "HIGH", counterArguments: "Corner sample had vanillin - supports contamination theory", isDiscriminating: "true", yearDiscovered: 2005 },
    { caseId, domain: "MATERIAL_SCIENCE", evidenceName: "WAXS aging matches Masada shroud (AD 70)", tier: "T2", source: "De Caro et al. 2022, Institute of Crystallography, Rome", whatItProves: "2000-year aging profile matches known 1st century textile", fabricationCost: "EXTREME", counterArguments: "Needs independent replication", isDiscriminating: "true", yearDiscovered: 2022 },
    { caseId, domain: "MATERIAL_SCIENCE", evidenceName: "Blood went on FIRST, image formed SECOND", tier: "T1", source: "STURP (Heller & Adler)", whatItProves: "Eliminates ALL forgery hypotheses - every artistic process is image-first, blood-second", fabricationCost: "IMPOSSIBLE", fabricationCostDescription: "No known technique produces blood-first, image-second", counterArguments: "Never seriously challenged, never overturned", isDiscriminating: "true", yearDiscovered: 1978 },
  ]);
  console.log("  Material science: 10 items");

  // ── EVIDENCE: DOMAIN 2 — HEMATOLOGY ──
  await db.insert(schema.evidenceItems).values([
    { caseId, domain: "HEMATOLOGY", evidenceName: "Type AB human male blood", tier: "T1", source: "Heller & Adler 1980-81, Baima Bollone", whatItProves: "Multiple independent confirmations - real human blood", fabricationCost: "EXTREME", fabricationCostDescription: "Requires actual human blood of specific type", counterArguments: "AB is common in Middle East; possible contamination from handling", isDiscriminating: "true", yearDiscovered: 1980 },
    { caseId, domain: "HEMATOLOGY", evidenceName: "Pre-mortem AND post-mortem blood (chemically distinct)", tier: "T1", source: "STURP hematological analysis", whatItProves: "Different chemistry, different locations - clinical precision", fabricationCost: "IMPOSSIBLE", fabricationCostDescription: "Hematology didn't exist until 19th century", counterArguments: "None", isDiscriminating: "true", yearDiscovered: 1978 },
    { caseId, domain: "HEMATOLOGY", evidenceName: "Post-mortem blood at side wound (rib 5-6)", tier: "T1", source: "STURP", whatItProves: "Consistent with John's Gospel - spear wound after death", fabricationCost: "EXTREME", counterArguments: "None", isDiscriminating: "true", yearDiscovered: 1978 },
    { caseId, domain: "HEMATOLOGY", evidenceName: "Pulmonary edema mixture (6:1 fluid to blood)", tier: "T2", source: "Hematological reports", whatItProves: "Consistent with crucifixion asphyxiation causing heart failure", fabricationCost: "EXTREME", counterArguments: "Specific ratio disputed by some pathologists", isDiscriminating: "true" },
    { caseId, domain: "HEMATOLOGY", evidenceName: "High creatinine = kidney failure", tier: "T2", source: "Blood chemistry analysis", whatItProves: "Consistent with torture/dehydration", fabricationCost: "HIGH", counterArguments: "Degradation over time affects readings", isDiscriminating: "false" },
    { caseId, domain: "HEMATOLOGY", evidenceName: "High ferritin = systemic inflammation", tier: "T2", source: "Blood chemistry analysis", whatItProves: "Consistent with scourging", fabricationCost: "HIGH", counterArguments: "Degradation concerns", isDiscriminating: "false" },
    { caseId, domain: "HEMATOLOGY", evidenceName: "~1/3 blood volume lost before death", tier: "T2", source: "Estimated from wound analysis", whatItProves: "Consistent with flagellation", fabricationCost: "HIGH", counterArguments: "Estimate, not measurement", isDiscriminating: "false" },
    { caseId, domain: "HEMATOLOGY", evidenceName: "Sudarium of Oviedo: separate artifact, also Type AB", tier: "T2", source: "Independent analysis", whatItProves: "Two artifacts, two countries, same blood type - independent confirmation", fabricationCost: "EXTREME", fabricationCostDescription: "Requires cross-artifact coordination", counterArguments: "Type AB common in region; may not be same individual", isDiscriminating: "true" },
  ]);
  console.log("  Hematology: 8 items");

  // ── EVIDENCE: DOMAIN 3 — PATHOLOGY ──
  await db.insert(schema.evidenceItems).values([
    { caseId, domain: "PATHOLOGY", evidenceName: "~700 total wounds estimated", tier: "T1", source: "STURP image analysis", whatItProves: "Front + back + estimated lateral - comprehensive torture record", fabricationCost: "EXTREME", counterArguments: "Lateral count is estimated", isDiscriminating: "false", yearDiscovered: 1978 },
    { caseId, domain: "PATHOLOGY", evidenceName: "200+ scourge marks (dorsal), 172+ (frontal)", tier: "T1", source: "STURP", whatItProves: "Dumbbell-shaped = Roman flagrum with lead tips", fabricationCost: "EXTREME", counterArguments: "None", isDiscriminating: "true", yearDiscovered: 1978 },
    { caseId, domain: "PATHOLOGY", evidenceName: "Two distinct scourge angles = two executioners", tier: "T1", source: "STURP", whatItProves: "Consistent with Roman practice", fabricationCost: "HIGH", counterArguments: "None", isDiscriminating: "false", yearDiscovered: 1978 },
    { caseId, domain: "PATHOLOGY", evidenceName: "50 puncture wounds on head (helmet, not wreath)", tier: "T1", source: "STURP", whatItProves: "Contradicts medieval art convention - medieval shows wreath", fabricationCost: "EXTREME", counterArguments: "None", isDiscriminating: "true", yearDiscovered: 1978 },
    { caseId, domain: "PATHOLOGY", evidenceName: "Nail wounds through wrists (not palms)", tier: "T1", source: "STURP", whatItProves: "Contradicts medieval art, confirmed by forensics - palms cannot support body weight", fabricationCost: "EXTREME", counterArguments: "None - anatomically correct", isDiscriminating: "true", yearDiscovered: 1978 },
    { caseId, domain: "PATHOLOGY", evidenceName: "Side wound between rib 5-6 (~3cm wide)", tier: "T1", source: "STURP", whatItProves: "Consistent with Roman spear (lancea)", fabricationCost: "HIGH", counterArguments: "None", isDiscriminating: "true", yearDiscovered: 1978 },
    { caseId, domain: "PATHOLOGY", evidenceName: "Right shoulder diagonal abrasions", tier: "T1", source: "STURP", whatItProves: "Patibulum (crossbeam) carrying marks", fabricationCost: "HIGH", counterArguments: "None", isDiscriminating: "false", yearDiscovered: 1978 },
    { caseId, domain: "PATHOLOGY", evidenceName: "Knee abrasions + nose tip trauma", tier: "T1", source: "STURP", whatItProves: "Forward fall under 125-lb crossbeam load", fabricationCost: "HIGH", counterArguments: "None", isDiscriminating: "false", yearDiscovered: 1978 },
  ]);
  console.log("  Pathology: 8 items");

  // ── EVIDENCE: DOMAIN 4 — BOTANICAL / GEOLOGICAL ──
  await db.insert(schema.evidenceItems).values([
    { caseId, domain: "BOTANICAL_GEOLOGICAL", evidenceName: "56 pollen species identified", tier: "T2", source: "Max Frei (5 years study)", whatItProves: "Geographic specificity - methodology criticized but not debunked", fabricationCost: "EXTREME", counterArguments: "Frei's methodology questioned; some pollen could be contaminants from display", isDiscriminating: "false", yearDiscovered: 1973 },
    { caseId, domain: "BOTANICAL_GEOLOGICAL", evidenceName: "Species blooming only in April in Jerusalem", tier: "T2", source: "Frei + Danin/Baruch 1999", whatItProves: "Seasonal + geographic specificity", fabricationCost: "EXTREME", fabricationCostDescription: "Requires trans-Mediterranean botanical knowledge 500 years early", counterArguments: "Pollen contamination from later handling possible", isDiscriminating: "false", yearDiscovered: 1999 },
    { caseId, domain: "BOTANICAL_GEOLOGICAL", evidenceName: "Provenance chain via pollen", tier: "T3", source: "Frei", whatItProves: "Jerusalem > Edessa > Constantinople > France > Turin", fabricationCost: "HIGH", counterArguments: "Chain is speculative; gaps exist", isDiscriminating: "false" },
    { caseId, domain: "BOTANICAL_GEOLOGICAL", evidenceName: "Jerusalem limestone/clay on feet", tier: "T2", source: "Soil analysis", whatItProves: "Native to Jerusalem", fabricationCost: "HIGH", counterArguments: "Could be from later pilgrimage handling", isDiscriminating: "false", yearDiscovered: 1978 },
    { caseId, domain: "BOTANICAL_GEOLOGICAL", evidenceName: "Jerusalem limestone/clay on knees", tier: "T2", source: "Soil analysis", whatItProves: "Consistent with falling", fabricationCost: "HIGH", counterArguments: "Contamination possible", isDiscriminating: "false", yearDiscovered: 1978 },
    { caseId, domain: "BOTANICAL_GEOLOGICAL", evidenceName: "Jerusalem limestone/clay on nose tip", tier: "T2", source: "Soil analysis", whatItProves: "Consistent with face-first collapse", fabricationCost: "HIGH", counterArguments: "Contamination possible", isDiscriminating: "false", yearDiscovered: 1978 },
  ]);
  console.log("  Botanical/Geological: 6 items");

  // ── EVIDENCE: DOMAIN 5 — IMAGING / PHYSICS ──
  await db.insert(schema.evidenceItems).values([
    { caseId, domain: "IMAGING_PHYSICS", evidenceName: "Photographic negative (discovered 1898)", tier: "T1", source: "Secondo Pia", whatItProves: "Positive image only visible through photographic inversion", fabricationCost: "IMPOSSIBLE", fabricationCostDescription: "Photography invented 500+ years later", counterArguments: "None - forger could not have understood negative imaging", isDiscriminating: "true", yearDiscovered: 1898 },
    { caseId, domain: "IMAGING_PHYSICS", evidenceName: "3D topographic information encoded", tier: "T1", source: "VP8 Image Analyzer (Jumper & Jackson 1976)", whatItProves: "No other image in history has this property - distance-correlated brightness", fabricationCost: "IMPOSSIBLE", fabricationCostDescription: "3D spatial encoding concept not formalized until 20th century", counterArguments: "None", isDiscriminating: "true", yearDiscovered: 1976 },
    { caseId, domain: "IMAGING_PHYSICS", evidenceName: "VUV radiation replicates chemical change", tier: "T1", source: "Di Lazzaro, ENEA Laboratories", whatItProves: "Peer-reviewed physics - vacuum ultraviolet radiation produces identical fibril change", fabricationCost: "EXTREME", counterArguments: "Cannot scale to full-body dimensions", isDiscriminating: "true", yearDiscovered: 2010 },
    { caseId, domain: "IMAGING_PHYSICS", evidenceName: "~34,000 billion watts peak power required", tier: "T1", source: "Di Lazzaro calculations", whatItProves: "1/40th billionth of a second - astronomical energy requirement", fabricationCost: "IMPOSSIBLE", counterArguments: "Theoretical calculation, not direct measurement", isDiscriminating: "false" },
    { caseId, domain: "IMAGING_PHYSICS", evidenceName: "Cannot scale to full-body dimensions", tier: "T1", source: "ENEA", whatItProves: "No existing technology can reproduce the image at body scale", fabricationCost: "IMPOSSIBLE", counterArguments: "Future technology might; not proof of mechanism", isDiscriminating: "true" },
    { caseId, domain: "IMAGING_PHYSICS", evidenceName: "Image only visible from 8+ feet", tier: "T1", source: "Direct observation", whatItProves: "Vanishes at close range - property of spatial frequency perception", fabricationCost: "EXTREME", counterArguments: "None", isDiscriminating: "true" },
  ]);
  console.log("  Imaging/Physics: 6 items");

  // ── EVIDENCE: DOMAIN 6 — HISTORICAL PROVENANCE ──
  await db.insert(schema.evidenceItems).values([
    { caseId, domain: "HISTORICAL_PROVENANCE", evidenceName: "Burial cloth mentioned in all four Gospels", tier: "T2", source: "Matthew, Mark, Luke, John", whatItProves: "Multiple attestation - early written sources", fabricationCost: "LOW", counterArguments: "Gospels are religious texts, not historical records", isDiscriminating: "false" },
    { caseId, domain: "HISTORICAL_PROVENANCE", evidenceName: "Eusebius reference (~325 AD)", tier: "T2", source: "Church historian, Council of Nicaea", whatItProves: "Earliest written reference to image cloth", fabricationCost: "LOW", counterArguments: "Reference is ambiguous; may not refer to Shroud", isDiscriminating: "false", yearDiscovered: 325 },
    { caseId, domain: "HISTORICAL_PROVENANCE", evidenceName: "Edessa period (~900 years)", tier: "T2", source: "Multiple historical sources", whatItProves: "Known as Mandylion / Image of Edessa", fabricationCost: "MODERATE", counterArguments: "Mandylion may be different artifact", isDiscriminating: "false" },
    { caseId, domain: "HISTORICAL_PROVENANCE", evidenceName: "Constantinople period", tier: "T2", source: "Byzantine records", whatItProves: "Documented transfer", fabricationCost: "MODERATE", counterArguments: "Records partially destroyed", isDiscriminating: "false" },
    { caseId, domain: "HISTORICAL_PROVENANCE", evidenceName: "Lirey France (Geoffrey de Charny, 1350s)", tier: "T1", source: "Historical record", whatItProves: "First European documentation - chain of custody begins", fabricationCost: "LOW", counterArguments: "Sudden appearance without provenance is suspicious", isDiscriminating: "false", yearDiscovered: 1353 },
    { caseId, domain: "HISTORICAL_PROVENANCE", evidenceName: "Savoy family (traded for two castles)", tier: "T1", source: "Historical record", whatItProves: "Chain of custody documented", fabricationCost: "LOW", counterArguments: "None", isDiscriminating: "false" },
    { caseId, domain: "HISTORICAL_PROVENANCE", evidenceName: "Catholic Church custody from 1983", tier: "T1", source: "Probate records", whatItProves: "Last Savoy king to Pope John Paul II", fabricationCost: "LOW", counterArguments: "None", isDiscriminating: "false", yearDiscovered: 1983 },
  ]);
  console.log("  Historical Provenance: 7 items");

  // ── EVIDENCE: DOMAIN 7 — DATING ──
  await db.insert(schema.evidenceItems).values([
    { caseId, domain: "DATING", evidenceName: "1988 C-14: 1260-1390 CE", tier: "T3", source: "Damon et al. 1989 (Nature)", whatItProves: "FROM CONTAMINATED CORNER SAMPLE - methodology compromised", fabricationCost: "LOW", counterArguments: "Multiple independent confirmations of contamination issues", isDiscriminating: "true", yearDiscovered: 1988 },
    { caseId, domain: "DATING", evidenceName: "Rogers: sample chemically different from main cloth", tier: "T1", source: "Thermochimica Acta 2005", whatItProves: "Cotton in sample (not linen), vanillin absent from main cloth", fabricationCost: "LOW", counterArguments: "Rogers had pro-authenticity bias; peer review questioned", isDiscriminating: "true", yearDiscovered: 2005 },
    { caseId, domain: "DATING", evidenceName: "WAXS: 2000-year aging profile", tier: "T2", source: "De Caro et al. 2022", whatItProves: "Matches Masada shroud (AD 70)", fabricationCost: "EXTREME", counterArguments: "Needs independent replication", isDiscriminating: "true", yearDiscovered: 2022 },
    { caseId, domain: "DATING", evidenceName: "Vanillin: zero remaining (main cloth)", tier: "T2", source: "Rogers 2005", whatItProves: "Medieval cloth would retain traces; zero indicates >1300 years", fabricationCost: "EXTREME", counterArguments: "Fires may have accelerated vanillin loss", isDiscriminating: "true", yearDiscovered: 2005 },
    { caseId, domain: "DATING", evidenceName: "Raw C-14 data suppressed 29 years", tier: "T1", source: "Casabianca et al. 2019", whatItProves: "British Museum released only after FOIA-equivalent; statistical heterogeneity", fabricationCost: "LOW", counterArguments: "Institutional caution, not conspiracy", isDiscriminating: "true", yearDiscovered: 2019 },
    { caseId, domain: "DATING", evidenceName: "Only 3 of 7 planned labs tested", tier: "T1", source: "Historical record", whatItProves: "No explanation for reduction; reduced statistical power", fabricationCost: "LOW", counterArguments: "Budget constraints", isDiscriminating: "true" },
    { caseId, domain: "DATING", evidenceName: "Sample from visibly contaminated corner", tier: "T1", source: "Visual inspection", whatItProves: "Anyone can see the discoloration - not representative", fabricationCost: "LOW", counterArguments: "Labs attempted to clean sample", isDiscriminating: "true" },
  ]);
  console.log("  Dating: 7 items");

  // ── EVIDENCE: DOMAIN 8 — ART HISTORICAL ──
  await db.insert(schema.evidenceItems).values([
    { caseId, domain: "ART_HISTORICAL", evidenceName: "200+ icons share facial features with Shroud", tier: "T2", source: "Iconographic studies", whatItProves: "Common source material indicated", fabricationCost: "MODERATE", counterArguments: "Icons copied each other, not necessarily Shroud", isDiscriminating: "false" },
    { caseId, domain: "ART_HISTORICAL", evidenceName: "Vignon markings (15-20 oddities)", tier: "T2", source: "Paul Vignon", whatItProves: "Systematic correspondence between Shroud and icons", fabricationCost: "MODERATE", counterArguments: "Selection bias in choosing which features to compare", isDiscriminating: "false" },
    { caseId, domain: "ART_HISTORICAL", evidenceName: "Byzantine coinage matches Shroud face", tier: "T2", source: "Numismatic studies", whatItProves: "Coins predate any proposed medieval hoax", fabricationCost: "MODERATE", counterArguments: "Coins are stylized, not photographic", isDiscriminating: "false" },
    { caseId, domain: "ART_HISTORICAL", evidenceName: "Pantocrator icon (6th century) overlaps Shroud", tier: "T2", source: "St. Catherine's Monastery", whatItProves: "Predates all medieval forgery dates", fabricationCost: "HIGH", counterArguments: "Overlapping features are generic", isDiscriminating: "false" },
    { caseId, domain: "ART_HISTORICAL", evidenceName: "Medieval art shows DIFFERENT Jesus", tier: "T2", source: "Art history", whatItProves: "Effeminate, no facial hair, nails in palms = NOT from Shroud - forger contradicted own era", fabricationCost: "EXTREME", counterArguments: "Shroud could have influenced art AFTER it appeared", isDiscriminating: "true" },
  ]);
  console.log("  Art Historical: 5 items");

  // ── TIMELINE ──
  await db.insert(schema.timelineEvents).values([
    { caseId, eventDate: "~30 AD", datePrecision: "YEAR", eventDescription: "Crucifixion of Jesus", source: "Gospels", verificationStatus: "CONFIRMED", tier: "T2" },
    { caseId, eventDate: "~325 AD", datePrecision: "YEAR", eventDescription: "Eusebius reference to image cloth at Council of Nicaea", source: "Eusebius, Church History", verificationStatus: "PROBABLE", tier: "T2" },
    { caseId, eventDate: "~400-944 AD", datePrecision: "DECADE", eventDescription: "Mandylion / Image of Edessa period (540+ years)", source: "Multiple historical sources", verificationStatus: "PROBABLE", tier: "T2", entitiesInvolved: "King Abgar V" },
    { caseId, eventDate: "~944-1204 AD", datePrecision: "DECADE", eventDescription: "Constantinople period", source: "Byzantine records", verificationStatus: "PROBABLE", tier: "T2" },
    { caseId, eventDate: "1204", datePrecision: "YEAR", eventDescription: "Fourth Crusade sacks Constantinople; relics dispersed", source: "Historical record", verificationStatus: "CONFIRMED", tier: "T1" },
    { caseId, eventDate: "~1353", datePrecision: "YEAR", eventDescription: "Shroud appears in Lirey, France (Geoffrey de Charny)", source: "Historical record", verificationStatus: "CONFIRMED", tier: "T1", entitiesInvolved: "Geoffrey de Charny" },
    { caseId, eventDate: "1389", datePrecision: "YEAR", eventDescription: "Bishop d'Arcis memo (draft, possibly never sent)", source: "d'Arcis memo", verificationStatus: "DISPUTED", tier: "T4", entitiesInvolved: "Bishop Pierre d'Arcis" },
    { caseId, eventDate: "1453", datePrecision: "YEAR", eventDescription: "Margaret de Charny transfers Shroud to House of Savoy (for 2 castles)", source: "Historical record", verificationStatus: "CONFIRMED", tier: "T1", entitiesInvolved: "Margaret de Charny, Duke Louis of Savoy" },
    { caseId, eventDate: "1532", datePrecision: "YEAR", eventDescription: "Chambery fire damages Shroud; molten silver burns through", source: "Historical record", verificationStatus: "CONFIRMED", tier: "T1" },
    { caseId, eventDate: "1578", datePrecision: "YEAR", eventDescription: "Shroud moved to Turin", source: "Historical record", verificationStatus: "CONFIRMED", tier: "T1", entitiesInvolved: "Emmanuel Philibert, Duke of Savoy" },
    { caseId, eventDate: "1898", datePrecision: "YEAR", eventDescription: "Secondo Pia photographs Shroud - discovers photographic negative", source: "Secondo Pia", verificationStatus: "CONFIRMED", tier: "T1", entitiesInvolved: "Secondo Pia" },
    { caseId, eventDate: "1931", datePrecision: "YEAR", eventDescription: "Giuseppe Enrie professional photographs confirm Pia's finding", source: "Giuseppe Enrie", verificationStatus: "CONFIRMED", tier: "T1", entitiesInvolved: "Giuseppe Enrie" },
    { caseId, eventDate: "1976", datePrecision: "YEAR", eventDescription: "VP8 Image Analyzer reveals 3D topographic encoding", source: "Jumper & Jackson", verificationStatus: "CONFIRMED", tier: "T1", entitiesInvolved: "Eric Jumper, John Jackson" },
    { caseId, eventDate: "1978", datePrecision: "YEAR", eventDescription: "STURP (Shroud of Turin Research Project) full scientific examination", source: "STURP team", verificationStatus: "CONFIRMED", tier: "T1", entitiesInvolved: "STURP (Heller, Adler, Rogers, Jumper, Jackson, Schwalbe, et al.)" },
    { caseId, eventDate: "1988", datePrecision: "YEAR", eventDescription: "C-14 dating: 1260-1390 CE (contaminated corner sample)", source: "Damon et al. 1989 (Nature)", verificationStatus: "DISPUTED", tier: "T3", entitiesInvolved: "British Museum, 3 labs" },
    { caseId, eventDate: "2005", datePrecision: "YEAR", eventDescription: "Rogers (Thermochimica Acta): sample chemically different from main cloth", source: "Ray Rogers", verificationStatus: "CONFIRMED", tier: "T1", entitiesInvolved: "Ray Rogers" },
    { caseId, eventDate: "2019", datePrecision: "YEAR", eventDescription: "Casabianca: British Museum releases raw C-14 data after 29-year suppression", source: "Casabianca et al.", verificationStatus: "CONFIRMED", tier: "T1" },
    { caseId, eventDate: "2022", datePrecision: "YEAR", eventDescription: "WAXS study: 2000-year aging profile matches Masada shroud (AD 70)", source: "De Caro et al., Institute of Crystallography, Rome", verificationStatus: "CONFIRMED", tier: "T2", entitiesInvolved: "Giuseppe De Caro, ENEA" },
  ]);
  console.log("  Timeline: 18 events");

  // ── FAKERY MATRIX F1-F10 ──
  await db.insert(schema.fakeryMatrixItems).values([
    { caseId, constraintId: "F1", constraintName: "Kill a man in a specific way", description: "Real human male blood - pre-mortem AND post-mortem, Type AB (6% population). Scourge with Roman flagrum from two angles (~372 dumbbell marks). Drive nails through wrists and heels. Stab between rib 5-6 AFTER death for post-mortem blood with pulmonary edema at 6:1 ratio. 125-lb crossbeam, face-first fall onto Jerusalem limestone.", fabricationCost: "EXTREME", fabricationCostDescription: "Requires actual murder with clinical precision", possibilityScore: "0.01", possibilityJustification: "Requires killing a person with exact wound specifications", rating: "EXTREME", sortOrder: 1 },
    { caseId, constraintId: "F2", constraintName: "Obtain Jerusalem-specific materials", description: "Soil from Jerusalem (specific limestone and clay) on feet, knees, and nose tip. Pollen from 56 plant species including species blooming ONLY in April in Jerusalem. Medieval France had no knowledge of Levantine spring-bloom species.", fabricationCost: "EXTREME", fabricationCostDescription: "Requires trans-Mediterranean botanical knowledge that didn't exist", possibilityScore: "0.01", possibilityJustification: "Botanical cataloging of Levant didn't exist in medieval Europe", rating: "EXTREME", sortOrder: 2 },
    { caseId, constraintId: "F3", constraintName: "Invent photography 500+ years early", description: "Image is a photographic negative. Positive only visible through photographic inversion (technology invented 1840s). Forger must create image indistinct to every viewer for 500 years.", fabricationCost: "IMPOSSIBLE", fabricationCostDescription: "Technology/concept that won't exist for 5 centuries", possibilityScore: "0", possibilityJustification: "Concept of negative/positive imaging unknown before 19th century", rating: "IMPOSSIBLE", sortOrder: 3 },
    { caseId, constraintId: "F4", constraintName: "Encode 3D information into 2D surface", description: "No painting, photograph, or print contains distance-correlated brightness data. VP8 image analyzer reveals topographic depth. Forger must understand 3D spatial encoding and apply brightness gradients correlating to body-to-cloth distance.", fabricationCost: "IMPOSSIBLE", fabricationCostDescription: "Concept didn't exist until 20th century", possibilityScore: "0", possibilityJustification: "3D spatial encoding formalized in 20th century, impossible to conceive earlier", rating: "IMPOSSIBLE", sortOrder: 4 },
    { caseId, constraintId: "F5", constraintName: "Apply image at exactly 2 microns depth", description: "Not with paint, dye, or any substance. Chemical change affects only outermost fibrils (top 0.2 microns of 150-200 fiber threads). No brush, stamp, contact transfer, or vapor method achieves this.", fabricationCost: "IMPOSSIBLE", fabricationCostDescription: "No known technology - medieval OR modern", possibilityScore: "0", possibilityJustification: "No existing technology can achieve this precision at body scale", rating: "IMPOSSIBLE", sortOrder: 5 },
    { caseId, constraintId: "F6", constraintName: "Make image survive fire and water", description: "Shroud survived at least 3 fires and water dousing. Any applied pigment, dye, or organic medium would degrade, smear, or wash out.", fabricationCost: "EXTREME", fabricationCostDescription: "Requires permanent chemical alteration of cellulose structure", possibilityScore: "0.01", possibilityJustification: "Requires molecular-level alteration inherently immune to fire/water", rating: "EXTREME", sortOrder: 6 },
    { caseId, constraintId: "F7", constraintName: "Know Roman crucifixion forensics with clinical precision", description: "Wound patterns contradict medieval art: nails through wrists (not palms), helmet of thorns (not wreath), naked (not loincloth), 5'10\" 175-180 lbs (not thin). Forger knew what modern forensic pathology confirmed.", fabricationCost: "EXTREME", fabricationCostDescription: "Requires forensic knowledge that contradicted contemporary convention", possibilityScore: "0.01", possibilityJustification: "All artistic convention contradicted the actual forensic evidence", rating: "EXTREME", sortOrder: 7 },
    { caseId, constraintId: "F8", constraintName: "Fake blood chemistry before blood chemistry existed", description: "Distinguish pre-mortem from post-mortem blood. Correct creatinine and ferritin levels. Pulmonary edema at correct ratio. Translucent serum halo. Hematology didn't exist until 19th century.", fabricationCost: "IMPOSSIBLE", fabricationCostDescription: "Requires science that didn't exist", possibilityScore: "0", possibilityJustification: "Blood chemistry as science emerged 19th century", rating: "IMPOSSIBLE", sortOrder: 8 },
    { caseId, constraintId: "F9", constraintName: "Get the blood type right", description: "Type AB - not identified until Landsteiner 1901. Must match Sudarium of Oviedo (separate artifact, separate country, separate provenance chain).", fabricationCost: "IMPOSSIBLE", fabricationCostDescription: "Requires knowledge 500+ years early AND cross-artifact coordination", possibilityScore: "0", possibilityJustification: "ABO typing invented 1901; cross-artifact coordination impossible", rating: "IMPOSSIBLE", sortOrder: 9 },
    { caseId, constraintId: "F10", constraintName: "Make image disappear at close range", description: "Image only visible from 8+ feet. Property of superficial fibril discoloration and human visual acuity interaction. No painting or applied image behaves this way.", fabricationCost: "EXTREME", fabricationCostDescription: "Requires understanding of spatial frequency perception", possibilityScore: "0.01", possibilityJustification: "Requires optics knowledge not available in medieval period", rating: "EXTREME", sortOrder: 10 },
  ]);
  console.log("  Fakery Matrix: F1-F10");

  // ── POPULATION DENSITY (Forger Profile) ──
  await db.insert(schema.populationDensityItems).values([
    { caseId, direction: "FORGERY", capability: "Forensic Pathologist (Roman crucifixion expertise)", locationRequired: "Lirey, France", eraRequired: "14th century", densityScore: "0", confidence: "HIGH", justification: "Forensic pathology as discipline did not exist until 19th century", populationEstimate: "0", sortOrder: 1 },
    { caseId, direction: "FORGERY", capability: "Hematologist (pre/post-mortem blood chemistry)", locationRequired: "Lirey, France", eraRequired: "14th century", densityScore: "0", confidence: "HIGH", justification: "Blood chemistry did not exist as science until 19th century", populationEstimate: "0", sortOrder: 2 },
    { caseId, direction: "FORGERY", capability: "Botanist (Levantine spring flora)", locationRequired: "Lirey, France", eraRequired: "14th century", densityScore: "0", confidence: "HIGH", justification: "No botanical catalog of Levantine species existed in medieval Europe", populationEstimate: "0", sortOrder: 3 },
    { caseId, direction: "FORGERY", capability: "Physicist (3D spatial encoding + VUV radiation)", locationRequired: "Lirey, France", eraRequired: "14th century", densityScore: "0", confidence: "HIGH", justification: "3D encoding concept and VUV physics not formalized until 20th century", populationEstimate: "0", sortOrder: 4 },
    { caseId, direction: "FORGERY", capability: "Photographer (negative/positive imaging)", locationRequired: "Lirey, France", eraRequired: "14th century", densityScore: "0", confidence: "HIGH", justification: "Photography invented 500+ years later", populationEstimate: "0", sortOrder: 5 },
    { caseId, direction: "FORGERY", capability: "Chemist (cellulose alteration at 2 microns)", locationRequired: "Lirey, France", eraRequired: "14th century", densityScore: "0", confidence: "HIGH", justification: "No known medieval or modern technique achieves this", populationEstimate: "0", sortOrder: 6 },
    { caseId, direction: "FORGERY", capability: "Person willing to commit specific murder for forgery", locationRequired: "Lirey, France", eraRequired: "14th century", densityScore: "0.001", confidence: "MEDIUM", justification: "Possible but no evidence of such a person; requires killing with clinical precision", populationEstimate: "<1", sortOrder: 7 },
    { caseId, direction: "FORGERY", capability: "ALL capabilities in ONE person", locationRequired: "Lirey, France", eraRequired: "14th century", densityScore: "0", confidence: "HIGH", justification: "Compound probability of all skills in one person: ZERO", populationEstimate: "0", sortOrder: 8 },
  ]);
  console.log("  Population Density: 8 items");

  // ── SOFT SIGNALS (14 signals) ──
  await db.insert(schema.softSignals).values([
    { caseId, signalName: "Narrative Compression", signalKey: "NARRATIVE_COMPRESSION", description: "Official explanation requires too many coincidences to be simultaneously true", score: "9.5", maxScore: "10", justification: "C-14 dating requires: contaminated sample, wrong corner, reduced labs, suppressed data, AND disparate results all aligning to same wrong date", evidenceRefs: "Casabianca 2019, Rogers 2005", sortOrder: 1 },
    { caseId, signalName: "Coincidence Density", signalKey: "COINCIDENCE_DENSITY", description: "Number of independent 'coincidences' required exceeds reasonable threshold", score: "9", maxScore: "10", justification: "8+ independent domains of evidence all converge on 1st century; each requires separate 'explanation'", evidenceRefs: "8-domain evidence catalog", sortOrder: 2 },
    { caseId, signalName: "Timing Friction", signalKey: "TIMING_FRICTION", description: "Events cluster suspiciously or critical moments lack temporal smoothness", score: "8", maxScore: "10", justification: "Shroud appears in France exactly when provenance chain gaps; 29-year data suppression timed around career advancement", evidenceRefs: "Timeline events, Casabianca 2019", sortOrder: 3 },
    { caseId, signalName: "Suppression Pressure", signalKey: "SUPPRESSION_PRESSURE", description: "Evidence or data is suppressed, delayed, or access-restricted", score: "9", maxScore: "10", justification: "British Museum suppressed raw C-14 data for 29 years; released only after FOIA-equivalent", evidenceRefs: "Casabianca et al. 2019", sortOrder: 4 },
    { caseId, signalName: "Documentary Disappearance", signalKey: "DOCUMENTARY_DISAPPEARANCE", description: "Key documents missing or destroyed at convenient moments", score: "6", maxScore: "10", justification: "d'Arcis memo is draft (possibly never sent); some Constantinople records lost", evidenceRefs: "d'Arcis memo 1389", sortOrder: 5 },
    { caseId, signalName: "Burden Inversion", signalKey: "BURDEN_INVERSION", description: "Burden of proof has been shifted from claimant to skeptic inappropriately", score: "7", maxScore: "10", justification: "Authenticity bears burden yet skeptics offer 'someone could have done it somehow' as counter-argument", evidenceRefs: "Skeptical objections analysis", sortOrder: 6 },
    { caseId, signalName: "Information Asymmetry", signalKey: "INFO_ASYMMETRY", description: "One side controls access to evidence or has privileged information", score: "7", maxScore: "10", justification: "Catholic Church controls physical access; British Museum controlled C-14 raw data", evidenceRefs: "1988 C-14 protocol", sortOrder: 7 },
    { caseId, signalName: "Expert Dissensus", signalKey: "EXPERT_DISSENSUS", description: "Domain experts are split in ways that correlate with non-evidential factors", score: "5", maxScore: "10", justification: "Split correlates with pre-commitment rather than expertise; STURP scientists (who examined) vs non-examiners", evidenceRefs: "STURP composition, Heller & Adler", sortOrder: 8 },
    { caseId, signalName: "Institutional Resistance", signalKey: "INSTITUTIONAL_RESISTANCE", description: "Established institutions resist updating positions despite new evidence", score: "6", maxScore: "10", justification: "Nature has not retracted 1989 C-14 paper despite known contamination; some institutions slow to acknowledge WAXS 2022", evidenceRefs: "Nature 1989, De Caro 2022", sortOrder: 9 },
    { caseId, signalName: "Replication Failure", signalKey: "REPLICATION_FAILURE", description: "Key claims cannot be replicated or reproduced by independent parties", score: "8", maxScore: "10", justification: "No one has reproduced Shroud image properties; all proposed techniques fail on multiple features", evidenceRefs: "Fakery Matrix F1-F10", sortOrder: 10 },
    { caseId, signalName: "Absence of Contradiction", signalKey: "ABSENCE_CONTRADICTION", description: "The authentic evidence set has no internal contradictions despite spanning 8 domains", score: "9", maxScore: "10", justification: "All 8 domains converge consistently; no evidence contradicts another", evidenceRefs: "Full evidence catalog", sortOrder: 11 },
    { caseId, signalName: "Predictive Success", signalKey: "PREDICTIVE_SUCCESS", description: "Position predicted findings before they were discovered", score: "7", maxScore: "10", justification: "VP8 3D encoding predicted by image properties; Vignon markings predicted common source", evidenceRefs: "VP8 1976, Vignon studies", sortOrder: 12 },
    { caseId, signalName: "Hostile Corroboration", signalKey: "HOSTILE_CORROBORATION", description: "Evidence confirmed by parties with incentive to disprove it", score: "8", maxScore: "10", justification: "STURP included skeptics; C-14 labs expected to confirm medieval date; all confirmed ancient properties", evidenceRefs: "STURP 1978, Heller & Adler", sortOrder: 13 },
    { caseId, signalName: "Noise Floor Check", signalKey: "NOISE_FLOOR", description: "Truth has noise; fabrication doesn't - authentic evidence has expected messiness", score: "7", maxScore: "10", justification: "Evidence is messy (some T2, some T3, disputes about C-14) but core findings are robust across independent sources", evidenceRefs: "Full evidence catalog", sortOrder: 14 },
  ]);
  console.log("  Soft Signals: 14 items");

  // ── PROTOCOL STEPS ──
  await db.insert(schema.protocolSteps).values([
    { caseId, stepNumber: 1, stepName: "THE PACT (Q0)", stepKey: "pact", description: "Both parties affirm truth exists and they want to find it more than they want to win. Diagnostic: if someone won't affirm this, the conversation isn't truth-seeking.", status: "COMPLETED", findings: "Protocol applied to Shroud case; truth-seeking posture established", conclusion: "PASS" },
    { caseId, stepNumber: 2, stepName: "Isolate the Exact Disagreement", stepKey: "isolate_disagreement", description: "Not the broad claim. The specific point of divergence. Most arguments that look total are about 1-2 assumptions.", status: "COMPLETED", findings: "Core disagreement: Is the Shroud a 1st century burial cloth with supernatural image formation, or a medieval forgery?", conclusion: "PASS - disagreement isolated" },
    { caseId, stepNumber: 3, stepName: "Competing Predictions", stepKey: "competing_predictions", description: "If Position A is true, what specific observable things must be true? If Position B is true, what specific observable things must be true? Where do predictions differ?", status: "COMPLETED", findings: "Authenticity predicts: ancient cloth, real blood, no pigments, 3D encoding, impossible to replicate. Forgery predicts: pigments, medieval materials, reproducible technique.", conclusion: "PASS - predictions mapped" },
    { caseId, stepNumber: 4, stepName: "The Update Commitment", stepKey: "update_commitment", description: "Both parties state IN ADVANCE what evidence would change their mind. If someone can't name anything: they're not truth-seeking.", status: "COMPLETED", findings: "Authenticity side: C-14 from clean sample + replication of image properties. Skeptic side: No specific update criteria stated.", conclusion: "Authenticity side passes; skeptic side fails update commitment" },
    { caseId, stepNumber: 5, stepName: "Evidence Classification", stepKey: "evidence_classification", description: "All evidence classified into tiers T1-T5 by fabrication cost, independence, and verifiability.", status: "COMPLETED", findings: "57 evidence items across 8 domains: 30 T1, 17 T2, 7 T3, 0 T4, 0 T5. Strong T1/T2 concentration.", conclusion: "PASS - evidence strongly weighted toward T1/T2" },
    { caseId, stepNumber: 6, stepName: "Independence Audit + Discriminating Evidence", stepKey: "independence_audit", description: "Verify source independence. Count only discriminating evidence where one position predicts X and other predicts Y.", status: "COMPLETED", findings: "Sources: STURP (independent team), ENEA (independent lab), De Caro (independent), Heller & Adler (independent). Multiple hostile corroborations.", conclusion: "PASS - independence verified" },
    { caseId, stepNumber: 7, stepName: "Coherence Test + Noise-Floor + Absence Audit", stepKey: "coherence_test", description: "Which position explains full evidence set with minimum complexity? Is story suspiciously clean? What evidence SHOULD exist?", status: "COMPLETED", findings: "Authenticity: single hypothesis (burial cloth of Jesus) explains all 8 domains. Forgery: requires 10+ independent ad hoc explanations. No suspicious absence detected.", conclusion: "PASS - authenticity more coherent" },
    { caseId, stepNumber: 8, stepName: "The Forced Inversion (Fakery Matrix)", stepKey: "forced_inversion", description: "Each side argues the OPPOSITE position. If YOUR claim is wrong, what would the world look like?", status: "COMPLETED", findings: "Fakery Matrix F1-F10: 5 IMPOSSIBLE, 5 EXTREME ratings. Compound probability functionally zero. No forgery hypothesis survives.", conclusion: "PASS - forgery impossible" },
    { caseId, stepNumber: 9, stepName: "The Solomon Test", stepKey: "solomon_test", description: "Judge designs scenario where truth-seeking and victory-seeking produce DIFFERENT behaviors. Observe choices.", status: "COMPLETED", findings: "Key test: Would authenticity advocates accept C-14 from clean sample if it shows medieval? YES stated. Skeptics: No specific criteria offered to accept authenticity.", conclusion: "Authenticity side passes Solomon Test" },
    { caseId, stepNumber: 10, stepName: "Honest Update", stepKey: "honest_update", description: "Based on all evidence: which position explains more with less? Which requires impossible capabilities?", status: "COMPLETED", findings: "Authenticity explains 8 domains with single hypothesis. Forgery requires impossible forger with zero population density. Population Density Test: ZERO.", conclusion: "UPDATE: Authenticity strongly supported" },
  ]);
  console.log("  Protocol Steps: 10");

  // ── ENTITIES ──
  await db.insert(schema.entities).values([
    { caseId, entityName: "Secondo Pia", entityType: "PERSON", knownFacts: "Amateur photographer who first photographed Shroud in 1898", disputedClaims: "None - role undisputed", connections: "Discovered photographic negative property" },
    { caseId, entityName: "Giuseppe Enrie", entityType: "PERSON", knownFacts: "Professional photographer, 1931 photographs", disputedClaims: "None", connections: "Confirmed Pia's discovery with higher quality" },
    { caseId, entityName: "Eric Jumper", entityType: "PERSON", knownFacts: "Air Force Academy, VP8 image analyzer discovery 1976", disputedClaims: "None", connections: "Co-discoverer of 3D encoding with John Jackson" },
    { caseId, entityName: "John Jackson", entityType: "PERSON", knownFacts: "Physicist, STURP team leader", disputedClaims: "None", connections: "VP8 discovery, STURP leadership" },
    { caseId, entityName: "Ray Rogers", entityType: "PERSON", knownFacts: "Los Alamos chemist, STURP team member", disputedClaims: "Pro-authenticity bias alleged by some", connections: "Thermochimica Acta 2005 paper on sample differences" },
    { caseId, entityName: "Paolo Di Lazzaro", entityType: "PERSON", knownFacts: "ENEA researcher, VUV radiation experiments", disputedClaims: "None", connections: "Peer-reviewed physics replication of Shroud image properties" },
    { caseId, entityName: "STURP", entityType: "ORGANIZATION", knownFacts: "Shroud of Turin Research Project, 1978", disputedClaims: "None on core findings; some questioned scope", connections: "30+ scientists, multiple institutions" },
    { caseId, entityName: "ENEA Laboratories", entityType: "INSTITUTION", knownFacts: "Italian National Agency for New Technologies", disputedClaims: "None", connections: "VUV radiation experiments" },
    { caseId, entityName: "British Museum", entityType: "INSTITUTION", knownFacts: "Custodian of C-14 dating protocol", disputedClaims: "Suppressed raw data for 29 years; reduced from 7 to 3 labs", connections: "1988 C-14 dating controversy" },
    { caseId, entityName: "Institute of Crystallography (Rome)", entityType: "INSTITUTION", knownFacts: "De Caro et al. WAXS study 2022", disputedClaims: "None", connections: "2000-year aging profile study" },
    { caseId, entityName: "Heller & Adler", entityType: "PERSON", knownFacts: "Blood chemists, STURP team", disputedClaims: "None on blood findings", connections: "Pre/post-mortem blood chemistry, blood-image sequence" },
    { caseId, entityName: "Walter McCrone", entityType: "PERSON", knownFacts: "Microscopist, claimed iron oxide = paint", disputedClaims: "Claim overruled by STURP team using better methods", connections: "Debunked pigment claim" },
    { caseId, entityName: "Geoffrey de Charny", entityType: "PERSON", knownFacts: "First documented European owner, 1350s", disputedClaims: "How he obtained Shroud is unknown", connections: "Lirey, France display" },
    { caseId, entityName: "House of Savoy", entityType: "ORGANIZATION", knownFacts: "Owned Shroud from ~1453 to 1983", disputedClaims: "None on ownership chain", connections: "Traded castles for Shroud; eventual transfer to Church" },
    { caseId, entityName: "Catholic Church", entityType: "INSTITUTION", knownFacts: "Custodian since 1983", disputedClaims: "Some claim institutional bias toward authenticity", connections: "Current custodian; John Paul II called Shroud 'mirror of the Gospel'" },
  ]);
  console.log("  Entities: 15");

  // ── CONTRADICTIONS ──
  await db.insert(schema.contradictions).values([
    { caseId, contradictionType: "OFFICIAL_NARRATIVE", description: "C-14 dating (1260-1390 CE) contradicts all other dating methods (WAXS, vanillin, historical provenance)", positionA: "C-14: medieval origin", positionB: "All other methods: ancient origin", severityScore: "8", resolution: "C-14 sample was contaminated corner; Rogers 2005 proved sample chemically different from main cloth" },
    { caseId, contradictionType: "SKEPTICAL", description: "Skeptical position requires accepting that a medieval forger had impossible knowledge across 8 domains", positionA: "Shroud is medieval forgery", positionB: "No forger could possess required skills (all rated IMPOSSIBLE/EXTREME)", severityScore: "9", resolution: "Fakery Matrix compound probability is functionally zero" },
    { caseId, contradictionType: "EVIDENTIAL", description: "McCrone's pigment claim contradicted by STURP team using superior methods", positionA: "McCrone: iron oxide = paint", positionB: "Heller & Adler: iron is from blood hemoglobin, not pigment", severityScore: "7", resolution: "STURP team overruled McCrone; chemical microanalysis > optical microscopy" },
    { caseId, contradictionType: "INTERNAL", description: "If Shroud is forged in 14th century, forger created image invisible for 500 years until photography invented", positionA: "Forger created image in 1350s", positionB: "Image only became visible with photography in 1898", severityScore: "9", resolution: "Impossible to explain - forger could not have understood negative imaging" },
  ]);
  console.log("  Contradictions: 4");

  console.log("\n=== SEED COMPLETE ===");
  console.log(`Case ID: ${caseId} (OI-CT-SHROUD)`);
  console.log("Total evidence items: 57");
  console.log("Timeline events: 18");
  console.log("Fakery constraints: 10");
  console.log("Population density items: 8");
  console.log("Soft signals: 14");
  console.log("Protocol steps: 10");
  console.log("Entities: 15");
  console.log("Contradictions: 4");
}

seed().catch(console.error);
